version: '3'
services:
  app:
    build: 
      context: .
      args:
        - BUILD_ENV=$BUILD_ENV
    ports:
      - "443:443"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: osaka
      MYSQL_DATABASE: osaka
      MYSQL_USER: osaka
      MYSQL_PASSWORD: osaka
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./docker_volume:/var/lib/mysql

