services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_ROOT_PASSWORD: osaka
      POSTGRES_DATABASE: osaka
      POSTGRES_USER: osaka
      POSTGRES_PASSWORD: osaka
    ports:
      - "5432:5432"
    volumes:
      - ./docker_volume:/var/lib/psql
