version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: osaka
      MYSQL_DATABASE: osaka
      MYSQL_USER: osaka
      MYSQL_PASSWORD: osaka
    ports:
      - "3306:3306"
    volumes:
      - ./docker_volume:/var/lib/mysql
